# SPDX-FileCopyrightText: 2026 Andrew Zhang <whisper67265@outlook.com>
#
# SPDX-License-Identifier: BSL-1.0

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2026 Andrew Zhang <whisper67265@outlook.com>"
SPDX-License-Identifier = "BSL-1.0"
path = "**/*"
