# SPDX-FileCopyrightText: 2026 Andrew Zhang <whisper67265@outlook.com>
#
# SPDX-License-Identifier: BSL-1.0

name: Build and check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-and-check:
    name: Build and check
    runs-on: ubuntu-latest
    steps:
    # actions/checkout v6.0.2
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    # actions/setup-python v6.2.0
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: '3.14'
    # astral-sh/setup-uv v8.1.0
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      with:
        enable-cache: false
        version: 0.11.12
    - name: uv build
      run: uv build
    - name: twine check
      run: uvx twine check dist/*
    - name: pydistcheck
      run: uvx pydistcheck --inspect dist/*
    - name: pyroma
      run: uvx --with pip pyroma .
    - name: check-wheel-contents
      run: uvx check-wheel-contents dist/*.whl
    - name: check-manifest
      run: uvx --with pip check-manifest -v
